const users = [
  {
    firstName: "John",
    lastName: "Stevenson",
    email: "john@gmail.com",
    password: "12345678",
    gender: "M",
    jobRole: "Accountant",
    department: "Finance",
    address: "Lagos, Nigeria",
  },
  {
    firstName: "Michael",
    lastName: "Johnson",
    email: "mike@gmail.com",
    password: "hjgfsdbvm",
    gender: "M",
    jobRole: "System Administrator",
    department: "IT",
    address: "Kampala, Uganda",
  },
  {
    firstName: "Reene",
    lastName: "Anderson",
    email: "reene@gmail.com",
    password: "nmoptyifg",
    gender: "F",
    jobRole: "Software Developer",
    department: "Software Development",
    address: "Nairobi, Kenya",
  },
  {
    firstName: "Samuel",
    lastName: "Jefferson",
    email: "samuel@gmail.com",
    password: "Samuel@123",
    gender: "M",
    jobRole: "Product Designer",
    department: "Product Design",
    address: "Accra, Ghana",
  },
  {
    firstName: "Kiza",
    lastName: "Sylvain",
    email: "sylvain@gmail.com",
    password: "sylvain8937",
    gender: "M",
    jobRole: "Project Management",
    department: "Business Development",
    address: "Cape Town, South Africa",
  },
  {
    firstName: "Valerie",
    lastName: "Simmons",
    email: "valerie@yahoo.com",
    password: "Valerie8993",
    gender: "F",
    jobRole: "Architect",
    department: "Construction",
    address: "Lagos, Nigeria",
  },
  {
    password: "mxcaqwspoy",
  },
  {
    email: "sylvain@gmail.com",
    password: "password",
  },
  {
    email: "user@gmail.com",
    password: "9746hdn547",
  },
];

export default users;
